### ISSUE TITLE
Enjoys the properties of parameter-free,

### ISSUE THREAD

**Issue by khawar-islam** [JunlinHan/YOCO#4]
Dear @JunlinHan 

Why do you called "which enjoys the properties of parameter-free". 
What do you mean by "parameter-free"?

**Comment by JunlinHan** [comment]
> Dear @JunlinHan
> 
> Why do you called "which enjoys the properties of parameter-free". What do you mean by "parameter-free"?

Hello Khawar,
The parameter here means learnable parameters, for instance, parameters of layers inside neural nets.
