### ISSUE TITLE
Missing Test top-1 error rate 

### ISSUE THREAD

**Issue by khawar-islam** [JunlinHan/YOCO#5]
Dear @JunlinHan 

Thank you for your work. I am working on your paper and reproducing the results given in the paper. I have trained a model based on your configuration for cifar-10 but I cannot find an error-rate file. How we can evaluate the top-1 error-rate?
**Like this**

```
print('Test\t  Prec@1: {top1.avg:.3f} (Err: {error:.3f} )\n'
          .format(top1=top1, error=100 - top1.avg))
```

**Comment by JunlinHan** [comment]
Hello khawar,
Simply calculate (1 - top1 rate) would give the error rate. 

Note CIFAR-10 results can be unstable (that is, results can be a little bit different between multiple trivals).
