### ISSUE TITLE
Calculating accuracy on CIFAR-10 multiple times or Single time

### ISSUE THREAD

**Issue by khawar-islam** [JunlinHan/YOCO#6]
Dear @JunlinHan,

Did you run all experiments multiple times than average and put them into the table? Like training resnet18 fives times and then averaging the accuracy and putting it into the table. Why I am asking this question because every time when I am training resnet18 I got different accuracy and error rate (almost 1% fluctuation).

Regards,
Khawar

**Comment by JunlinHan** [comment]
Hello @khawar-islam  ,
Unstable results between multiple runs are quite common. Our reported results in the paper should be the mean of 3 individual trials (for CIFAR datasets). We also report SD in the appendix.
You may run your experiment 5 times and report the mean number, which should be more stable and representative.
