### ISSUE TITLE
Same data augmentation but different instance

### ISSUE THREAD

**Issue by qsunyuan** [JunlinHan/YOCO#7]
很有意思的工作，简单有效！

一个小疑惑，为什么要都是采用相同（same type）的数据增强方法用于两个cuts呢？看了下ablation，似乎是关于位置的和cuts数目的消融实验。

会不会不同的cuts用不同的数据增强更好呢？

比如说：一部分颜色变换，另一部分旋转反转。

**Comment by JunlinHan** [comment]
Hello,
谢谢对我们工作的关注！

为什么要都是采用相同（same type）的数据增强方法用于两个cuts呢？ -> 这篇文章主要的关注点是，对于一个augmentation，应该做在image level还是local level，故没有深入多个augmentation混合使用的情况。

会不会不同的cuts用不同的数据增强更好呢？ -> 是的，这是非常有可能的，有一篇patch autoaugment有做这个思路，请查看: https://arxiv.org/pdf/2103.11099.pdf

希望有帮助！
